### PR TITLE
Delete int_project directory

### PR DESCRIPTION
**Pull request by benendles**

### CODE REVIEW

**Comment by benendles** [comment]
deleted to better organize it

**Review by ProDaryl — APPROVED** [review]

**Review by ProDaryl — COMMENTED** [review]
Use your own branch

**Comment by benendles** [comment]
Which branch


Le mer. 21 août 2024 à 5:20 soir, ProDaryl ***@***.***> a
écrit :

**Comment by ProDaryl** [comment]
The chat branch
U can work there

**Comment by benendles** [comment]
Thanks for the tip!

Le mer. 21 août 2024 à 5:25 soir, ProDaryl ***@***.***> a
écrit :

> The chat branch
> U can work there
>

**Comment by ProDaryl** [comment]
No problem
Just make sure to finish the project this week
I’ll buy the domain name before Friday

**Pull request merged**
